//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HireEng
    {
        public int Id { get; set; }
        public Nullable<int> Sid { get; set; }
        public Nullable<int> Eid { get; set; }
        public string RequestText { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string Accept { get; set; }
        public string EngineerName { get; set; }
        public string engineerAddress { get; set; }
    }
}
