//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Post
    {
        public int id { get; set; }
        public Nullable<int> build_id { get; set; }
        public Nullable<int> Ser_id { get; set; }
        public string Land_Size { get; set; }
        public string Description { get; set; }
        public Nullable<int> Location { get; set; }
        public string Price { get; set; }
        public Nullable<int> LocID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Address { get; set; }
        public string Building_Name { get; set; }
        public string LocationName { get; set; }
        public string Email { get; set; }
        public string Contact_Number { get; set; }
    
        public virtual BuildingType BuildingType { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
