//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        public ServiceType()
        {
            this.Job_Post = new HashSet<Job_Post>();
        }
    
        public int id { get; set; }
        public string SerType { get; set; }
    
        public virtual ICollection<Job_Post> Job_Post { get; set; }
    }
}
